apiVersion: v1
kind: Service
metadata:
  name: {{ include "vizdiff.fullname" . }}-api
  labels:
    {{- include "vizdiff.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "vizdiff.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
