export const PRICING_PLANS = [
  {
    name: "Starter",
    monthlyPrice: "49",
    annualMonthlyPrice: "39.17",
    monthlyUrl: "/signup?interval=monthly&plan=starter",
    annualUrl: "/signup?interval=yearly&plan=starter",
    features: [
      "15,000 screenshots per month",
      "$0.005 per additional screenshot",
      "30-day retention of historical screenshots",
      "Unlimited users",
      "GitHub Actions integration",
      "Single Sign-On (SSO) via GitHub",
    ],
    ctaText: "Select plan",
  },
  {
    name: "Team",
    monthlyPrice: "149",
    annualMonthlyPrice: "119.17",
    monthlyUrl: "/signup?interval=monthly&plan=team",
    annualUrl: "/signup?interval=yearly&plan=team",
    features: [
      "60,000 screenshots per month",
      "$0.004 per additional screenshot",
      "30-day retention of historical screenshots",
      "Unlimited users",
      "GitHub Actions integration",
      "Single Sign-On (SSO) via GitHub",
    ],
    ctaText: "Select plan",
  },
  {
    name: "Pro",
    monthlyPrice: "499",
    annualMonthlyPrice: "399.17",
    monthlyUrl: "/signup?interval=monthly&plan=pro",
    annualUrl: "/signup?interval=yearly&plan=pro",
    features: [
      "250,000 screenshots per month",
      "$0.004 per additional screenshot",
      "90-day retention of historical screenshots",
      "Unlimited users",
      "GitHub Actions integration",
      "Single Sign-On (SSO) via GitHub",
    ],
    ctaText: "Select plan",
  },
]
