extends:
  - plugin:@foxglove/base
  - plugin:@foxglove/jest

env:
  node: true

ignorePatterns:
  - dist

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@foxglove/typescript
    parserOptions:
      project: ./tsconfig.json
      tsconfigRootDir: api
      EXPERIMENTAL_useProjectService: true
    rules:
      "@typescript-eslint/restrict-template-expressions": "off"
      "@typescript-eslint/strict-boolean-expressions": "off"
      "@typescript-eslint/no-misused-promises": ["error", { "checksVoidReturn": false }]
      "@typescript-eslint/promise-function-async": "off"
