name: Dedupe Dependabot PRs

on:
  push:
    branches: ["dependabot/**"]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  dedupe:
    name: Dedupe Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Dedupe dependencies
        run: yarn dedupe

      - name: Commit changes
        run: |
          git add .
          git commit -m '[dependabot skip] Dedupe dependencies' || true

      - name: Push changes
        run: git push
